rootProject.name = "keth"

include("rlp")
include("collections")
include("codegen")
include("contract")
include("contract:abi")
include("contract:generator")
include("contract:solidity-plugin")
include("ethereum")
include("ethereum:rpc-client")
include("ethereum:type")
include("ethereum:state")
include("ethereum:vm")
include("ethereum:chain")
include("ethereum:hardfork")
